###
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "username": "wndn@gmail.com",
  "password": "haesol2",
  "lastName": "두",
  "firstName": "해솔",
  "nickname": "ssols",
  "phoneNum": "01049380425",
  "gender": "1"
}

###
POST http://localhost:8080/mail/check
Content-Type: application/json

{
  "authMail": "wndn@gmail.com",
  "key": "WLE8437"
}

###
//로그인
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "wndn@gmail.com",
  "password": "haesol2"
}